### ISSUE TITLE
How to connect to cloud mongo?

### ISSUE THREAD

**Issue by Jytesh** [lukechilds/keyv-mongo#32]
```js
const db = "mongo-test"
const uri = `mongodb+srv://${pass}@free-tqvaj.mongodb.net/test?retryWrites=true&w=majority/${db}`
const keyv = new Keyv(uri);
async function main(){
    keyv.on('error', err => console.log('Connection Error', err));
    await keyv.set("BOI",1)

}
main()
```
Gives error => `assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: missing path
  `

**Comment by ChrisLahaye** [comment]
@Jytesh Seems like mongodb+srv isn't supported. Did you find any good alternative?

**Comment by Jytesh** [comment]
Nope.How would I connect to a remote mongoDB server then(I am using Cloud Atlas)

**Comment by ChrisLahaye** [comment]
@Jytesh in Atlas you can only deploy MongoDB clusters. Since you have at least three nodes you have to use SRV records instead of a single A record, this is not supported by the used driver. What you can do is extract one of the nodes and connect to that one explicitly.

**Comment by Jytesh** [comment]
I will try that then.

**Comment by Jytesh** [comment]
How do i do that though

**Comment by ChrisLahaye** [comment]
@Jytesh check #33 for a solution

**Comment by Albert-J04** [comment]
I was having this issue also - without finding a lot of help. 
Found a solution:

In Atlas choose "Connect Cluster" --> Connect your application using native --> Choose Node JS and version **2.2.12 or later** - that way you will get a `mongodb://`  instead of `mongodb+srv://`

**Comment by Jytesh** [comment]
Oh nice thanks
