### ISSUE TITLE
Replace mongojs by official mongodb driver

### ISSUE THREAD

**Issue by ChrisLahaye** [lukechilds/keyv-mongo#33]
Hello,

Would you accept a PR to replace mongojs by the official MongoDB driver for mongodb+srv support?

Best

**Comment by chroventer** [comment]
`mongojs` does support `mongodb-srv` URIs, but `keyv` only infers URIs prefixed with `mongodb`.

Here's a workaround:
```js 
const Keyv = require("keyv");
const KeyvMongo = require("@keyv/mongo");

const store = new KeyvMongo("mongo-srv://...");
const db = new Keyv({ store });
```

**Comment by Jytesh** [comment]
Hey, tried this but got MongoError: failed to connect to server [free.tqvaj.mongodb.net:27017] on first connect [MongoError: getaddrinfo ENOTFOUND myurl]

I know the url is solid as I connected with mongodb fine, it just doesn't work with mongojs
